config/routes.rb
Rails.application.routes.draw do
  resources :cinema_films
  resources :film_genres
  resources :genres
  resources :film_participants
  resources :participants
  resources :films
  resources :cinemas
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

end

app/models/film_genre.rb
class FilmGenre < ActiveRecord::Base
  belongs_to :film
  belongs_to :genre

  validates :genre, :film, presence: true

  before_create :check_genres

  private

  def check_genres
    return true if FilmGenre.where(film_id: self.film_id).count < 20
    return false
  end
end

app/controllers/film_genres_controller.rb
class FilmGenresController < ApplicationController
  before_action :set_film_genre, only: [:show, :edit, :update, :destroy]

  # GET /film_genres
  # GET /film_genres.json
  def index
    @film_genres = FilmGenre.all
  end

  # GET /film_genres/1
  # GET /film_genres/1.json
  def show
  end

  # GET /film_genres/new
  def new
    @film_genre = FilmGenre.new
  end

  # GET /film_genres/1/edit
  def edit
  end

  # POST /film_genres
  # POST /film_genres.json
  def create
    @film_genre = FilmGenre.new(film_genre_params)

    respond_to do |format|
      if @film_genre.save
        format.html { redirect_to @film_genre, notice: 'Film genre was successfully created.' }
        format.json { render :show, status: :created, location: @film_genre }
      else
        format.html { render :new }
        format.json { render json: @film_genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /film_genres/1
  # PATCH/PUT /film_genres/1.json
  def update
    respond_to do |format|
      if @film_genre.update(film_genre_params)
        format.html { redirect_to @film_genre, notice: 'Film genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @film_genre }
      else
        format.html { render :edit }
        format.json { render json: @film_genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /film_genres/1
  # DELETE /film_genres/1.json
  def destroy
    @film_genre.destroy
    respond_to do |format|
      format.html { redirect_to film_genres_url, notice: 'Film genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film_genre
      @film_genre = FilmGenre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_genre_params
      params.require(:film_genre).permit(:film_id, :genre_id)
    end
end

app/helpers/film_genres_helper.rb
module FilmGenresHelper
end

app/views/film_genres/_form.html.haml
= form_for @film_genre do |f|
  - if @film_genre.errors.any?
    #error_explanation
      %h2= "#{pluralize(@film_genre.errors.count, "error")} prohibited this film_genre from being saved:"
      %ul
        - @film_genre.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :film_id
    = f.text_field :film_id
  .field
    = f.label :genre_id
    = f.text_field :genre_id
  .actions
    = f.submit 'Сохранить'

app/views/film_genres/edit.html.haml
%h1 Editing film_genre

= render 'form'

= link_to 'Показать', @film_genre
\|
= link_to 'Назад', film_genres_path

app/views/film_genres/index.html.haml
%h1 Listing film_genres

%table
  %thead
    %tr
      %th Film_id
      %th Genre_id
      %th
      %th
      %th

  %tbody
    - @film_genres.each do |film_genre|
      %tr
        %td= film_genre.film_id
        %td= film_genre.genre_id
        %td= link_to 'Показать', film_genre
        %td= link_to 'Изменить', edit_film_genre_path(film_genre)
        %td= link_to 'Удалить', film_genre, method: :delete, data: { confirm: 'Вы уверены?' }

%br

= link_to 'Новый жанр фильма', new_film_genre_path

app/views/film_genres/new.html.haml
%h1 New film_genre

= render 'form'

= link_to 'Назад', film_genres_path

app/views/film_genres/show.html.haml
%p#notice= notice

%p
  %b Film:
  = @film_genre.film_id
%p
  %b Genre:
  = @film_genre.genre_id

= link_to 'Изменить', edit_film_genre_path(@film_genre)
\|
= link_to 'Назад', film_genres_path