config/routes.rb
Rails.application.routes.draw do
  resources :cinema_films
  resources :film_genres
  resources :genres
  resources :film_participants
  resources :participants
  resources :films
  resources :cinemas
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

end

app/models/participant.rb
class Participant < ActiveRecord::Base
  has_many :film_participants
  has_many :films, through: :film_participants

  validates :name, :surname, :birthday, presence: true
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to participants_url, notice: 'Participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:name, :surname, :birthday)
    end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.haml
= form_for @participant do |f|
  - if @participant.errors.any?
    #error_explanation
      %h2= "#{pluralize(@participant.errors.count, "error")} prohibited this participant from being saved:"
      %ul
        - @participant.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :surname
    = f.text_field :surname
  .field
    = f.label :birthday
    = f.date_select :birthday
  .actions
    = f.submit 'Сохранить'

app/views/participants/edit.html.haml
.page-header
  %h1= t('headers.participants.edit')

= render 'form'

= link_to 'Показать', @participant
\|
= link_to 'Назад', participants_path

app/views/participants/index.html.haml
.page-header
  %h1= t('headers.participants.index')

%table.table.table-hover.table-striped.center
  %thead
    %tr
      %th= Participant.human_attribute_name(:name)
      %th= Participant.human_attribute_name(:surname)
      %th= Participant.human_attribute_name(:birthday)
      %th
      %th
      %th

  %tbody
    - @participants.each do |participant|
      %tr
        %td= participant.name
        %td= participant.surname
        %td= participant.birthday
        %td= link_to 'Показать', participant
        %td= link_to 'Изменить', edit_participant_path(participant)
        %td= link_to 'Удалить', participant, method: :delete, data: { confirm: 'Вы уверены?' }

%br

= link_to 'Новый участник', new_participant_path

app/views/participants/new.html.haml
.page-header
  %h1= t('headers.participants.new')

= render 'form'

= link_to 'Назад', participants_path

app/views/participants/show.html.haml
%p#notice= notice

%p
  %b= Participant.human_attribute_name(:name)
  = @participant.name
%p
  %b= Participant.human_attribute_name(:surname)
  = @participant.surname
%p
  %b= Participant.human_attribute_name(:birthday)
  = @participant.birthday

= link_to 'Изменить', edit_participant_path(@participant)
\|
= link_to 'Назад', participants_path