config/routes.rb
Rails.application.routes.draw do
  resources :cinema_films
  resources :film_genres
  resources :genres
  resources :film_participants
  resources :participants
  resources :films
  resources :cinemas
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

end

app/models/film.rb
class Film < ActiveRecord::Base
  has_many :film_participants, :dependent => :destroy
  has_many :participant, through: :film_participants

  has_many :film_genres
  has_many :genres, through: :film_genres

  has_many :cinema_films
  has_many :cinemas, through: :cinema_films

  validates :name, :duration, :country, :cinemacompany, presence: true
  validates :minage, inclusion: { in: 0..18 }
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]

  # GET /films
  # GET /films.json
  def index
    @films = Film.all
  end

  # GET /films/1
  # GET /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url, notice: 'Film was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_params
      params.require(:film).permit(:name, :genre, :duration, :country, :cinemacompany, :minage)
    end
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_form.html.haml
= form_for @film do |f|
  - if @film.errors.any?
    #error_explanation
      %h2= "#{pluralize(@film.errors.count, "error")} prohibited this film from being saved:"
      %ul
        - @film.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :duration
    = f.text_field :duration
  .field
    = f.label :country
    = f.text_field :country
  .field
    = f.label :cinemacompany
    = f.text_field :cinemacompany
  .field
    = f.label :minage
    = f.text_field :minage
  .actions
    = f.submit 'Save'

app/views/films/edit.html.haml
.page-header
  %h1= t('headers.films.edit')

= render 'form'

= link_to 'Показать', @film
\|
= link_to 'Назад', films_path

app/views/films/index.html.haml
.page-header
  %h1= t('headers.films.index')

%table.table.table-hover.table-striped.center
  %thead
    %tr
      %th= Film.human_attribute_name(:name)
      %th= Film.human_attribute_name(:duration)
      %th= Film.human_attribute_name(:country)
      %th= Film.human_attribute_name(:cinemacompany)
      %th= Film.human_attribute_name(:minage)
      %th
      %th
      %th

  %tbody
    - @films.each do |film|
      %tr
        %td= film.name
        %td= film.duration
        %td= film.country
        %td= film.cinemacompany
        %td= film.minage
        %td= link_to 'Показать', film
        %td= link_to 'Изменить', edit_film_path(film)
        %td= link_to 'Удалить', film, method: :delete, data: { confirm: 'Вы уыерены?' }

%br

= link_to 'Новый фильм', new_film_path

app/views/films/new.html.haml
.page-header
  %h1= t('headers.films.new')

= render 'form'

= link_to 'Назад', films_path

app/views/films/show.html.haml
%p#notice= notice

%p
  %b= Film.human_attribute_name(:name)
  = @film.name
%p
  %b= Film.human_attribute_name(:duration)
  = @film.duration
%p
  %b= Film.human_attribute_name(:country)
  = @film.country
%p
  %b= Film.human_attribute_name(:cinemacompany)
  = @film.cinemacompany
%p
  %b= Film.human_attribute_name(:minage)
  = @film.minage

= link_to 'Изменить', edit_film_path(@film)
\|
= link_to 'Назад', films_path